---
apiVersion: v1
kind: Template
metadata:
  name: catalog-tower-persister
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: catalog-tower-persister
  spec:
    envName: ${ENV_NAME}
    pods:
    - name: service
      image: ${IMAGE}:${IMAGE_TAG}
      minReplicas: ${{MIN_REPLICAS}}
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /health
          port: 8000
          scheme: HTTP
        initialDelaySeconds: 35
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 120
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /ready
          port: 8000
          scheme: HTTP
        initialDelaySeconds: 35
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 120
      env:
      - name: LOG_LEVEL
        value: ${LOG_LEVEL}
      - name: CLOWDER_ENABLED
        value: ${CLOWDER_ENABLED}
      resources:
        limits:
          cpu: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
        requests:
          cpu: 200m
          memory: 256Mi
      web: true
      volumes:
      - emptyDir: {}
        name: tmpdir
      volumeMounts:
      - mountPath: /tmp
        name: tmpdir
    kafkaTopics:
    - topicName: platform.catalog.persister
    database:
      name: catalog_inventory_production
      sharedDbAppName: catalog-inventory
    dependencies:
    - catalog-inventory

parameters:
- name: LOG_LEVEL
  value: INFO
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- name: MIN_REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Image name
  name: IMAGE
  value: quay.io/cloudservices/catalog_tower_persister
- description: Determines Clowder deployment
  name: CLOWDER_ENABLED
  value: "True"
- description: ClowdEnv Name
  name: ENV_NAME
  required: false
